version: 2

sources:
  - name: staging
    database: "{{ env_var('GCP_PROJECT_ID') }}"
     # For postgres:
      #database: production
    schema: "{{ env_var('GCP_DATASET') }}"

    tables:
      - name: transactions
      - name: product
      - name: store

models:
    - name: transactions
    - name: product
    - name: store